// Generated by bun-plugin-auto-imports
//
// Name to file, relative to this file. The resolvers read it, and the name
// types are `keyof` over it - so a name that type-checks is a name that
// resolves. Values are paths rather than import thunks on purpose: thunks
// would make every compilation that touches a name resolve every module.
export const emails = {
  'password-reset': '../../../resources/emails/password-reset.stx',
  'quota-warning': '../../../resources/emails/quota-warning.stx',
  'report-delivery': '../../../resources/emails/report-delivery.stx',
  'subscription-confirmation': '../../../resources/emails/subscription-confirmation.stx',
  'email-verification': '../defaults/resources/emails/email-verification.stx',
  'password-changed': '../defaults/resources/emails/password-changed.stx',
  'team-invitation': '../defaults/resources/emails/team-invitation.stx',
  'welcome': '../defaults/resources/emails/welcome.stx',
  'layouts/base': '../defaults/resources/emails/layouts/base.html',
} as const
