// Generated by bun-plugin-auto-imports

// This file injects auto-imported functions into the global scope
// Import this file early in your application startup

import * as autoImports from './index'

// Inject into globalThis for runtime access
Object.assign(globalThis, autoImports)

// TypeScript declarations
declare global {
  const increment: typeof autoImports.increment
  const decrement: typeof autoImports.decrement
  const reset: typeof autoImports.reset
  const count: typeof autoImports.count
  const toggleDark: typeof autoImports.toggleDark
  const isDark: typeof autoImports.isDark
  const preferredDark: typeof autoImports.preferredDark
  const seriesColor: typeof autoImports.seriesColor
  const compact: typeof autoImports.compact
  const money: typeof autoImports.money
  const delta: typeof autoImports.delta
  const plotArea: typeof autoImports.plotArea
  const niceCeiling: typeof autoImports.niceCeiling
  const ticks: typeof autoImports.ticks
  const timeLabels: typeof autoImports.timeLabels
  const shortDate: typeof autoImports.shortDate
  const longDate: typeof autoImports.longDate
  const linePath: typeof autoImports.linePath
  const areaPath: typeof autoImports.areaPath
  const bars: typeof autoImports.bars
  const donut: typeof autoImports.donut
  const needsLegend: typeof autoImports.needsLegend
  const SERIES_SLOTS: typeof autoImports.SERIES_SLOTS
  const DEFAULT_BOX: typeof autoImports.DEFAULT_BOX
}

export {}
