-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "usage_counters" (
  "id" BIGSERIAL PRIMARY KEY,
  "project_id" bigint not null REFERENCES "projects"("id"),
  "month" varchar(7) not null,
  "events" integer default 0,
  "rejected" integer default 0,
  "notified_at_percent" integer default 0,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "usage_counters_project_month_unique" ON "usage_counters" ("project_id", "month");
