-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "project_members" (
  "id" BIGSERIAL PRIMARY KEY,
  "project_id" bigint not null REFERENCES "projects"("id"),
  "user_id" bigint not null REFERENCES "users"("id"),
  "email" varchar(255),
  "role" "project_members_role_type" default 'member',
  "invited_by_id" integer,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "project_members_project_user_unique" ON "project_members" ("project_id", "user_id");
CREATE INDEX IF NOT EXISTS "project_members_user_index" ON "project_members" ("user_id");
