-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "report_blocks" (
  "id" BIGSERIAL PRIMARY KEY,
  "report_id" bigint not null REFERENCES "reports"("id"),
  "kind" "report_blocks_kind_type" not null,
  "title" varchar(120),
  "x" integer default 0,
  "y" integer default 0,
  "w" integer default 6,
  "h" integer default 4,
  "query" text,
  "viz" text,
  "body" text,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "report_blocks_report_index" ON "report_blocks" ("report_id");
