-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "projects" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(100) not null,
  "slug" varchar(120),
  "ingest_key" varchar(80),
  "timezone" varchar(64) default 'UTC',
  "auto_reports_enabled" boolean default true,
  "first_event_at" varchar(255),
  "owner_id" bigint REFERENCES "users"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "deleted_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "projects_ingest_key_unique" ON "projects" ("ingest_key");
CREATE INDEX IF NOT EXISTS "projects_owner_index" ON "projects" ("owner_id");
CREATE UNIQUE INDEX IF NOT EXISTS "projects_ingest_key_unique" ON "projects" ("ingest_key");
CREATE UNIQUE INDEX IF NOT EXISTS "projects_uuid_unique" ON "projects" ("uuid");
