-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "reports" (
  "id" BIGSERIAL PRIMARY KEY,
  "project_id" bigint not null REFERENCES "projects"("id"),
  "name" varchar(120) not null,
  "slug" varchar(140),
  "description" varchar(500),
  "status" "reports_status_type" default 'draft',
  "published_at" varchar(255),
  "unpublished_changes" boolean default false,
  "origin" "reports_origin_type" default 'user',
  "template_key" varchar(120),
  "template_version" integer,
  "default_range" varchar(40) default 'last_30_days',
  "created_by_id" bigint REFERENCES "users"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "deleted_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "reports_project_slug_unique" ON "reports" ("project_id", "slug");
CREATE INDEX IF NOT EXISTS "reports_project_template_index" ON "reports" ("project_id", "template_key");
CREATE UNIQUE INDEX IF NOT EXISTS "reports_uuid_unique" ON "reports" ("uuid");
