-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "event_rollups" (
  "id" BIGSERIAL PRIMARY KEY,
  "project_id" bigint not null REFERENCES "projects"("id"),
  "day" varchar(10) not null,
  "name" varchar(120) not null,
  "event_count" integer default 0,
  "value_sum" integer default 0,
  "value_count" integer default 0,
  "value_min" integer,
  "value_max" integer,
  "unique_users" integer default 0,
  "built_at" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "event_rollups_unique" ON "event_rollups" ("project_id", "day", "name");
CREATE INDEX IF NOT EXISTS "event_rollups_project_day_index" ON "event_rollups" ("project_id", "day");
