-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "events" (
  "id" BIGSERIAL PRIMARY KEY,
  "project_id" bigint not null REFERENCES "projects"("id"),
  "name" varchar(120) not null,
  "occurred_at" varchar(255) not null,
  "received_at" varchar(255),
  "properties" text,
  "value" real,
  "currency" varchar(3),
  "user_key" varchar(120),
  "session_key" varchar(120)
);
CREATE INDEX IF NOT EXISTS "events_project_name_time_index" ON "events" ("project_id", "name", "occurred_at");
CREATE INDEX IF NOT EXISTS "events_project_time_index" ON "events" ("project_id", "occurred_at");
CREATE INDEX IF NOT EXISTS "events_project_user_index" ON "events" ("project_id", "user_key");
