-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "report_revisions" (
  "id" BIGSERIAL PRIMARY KEY,
  "report_id" bigint not null REFERENCES "reports"("id"),
  "snapshot" text not null,
  "reason" "report_revisions_reason_type" default 'autosave',
  "created_by_id" bigint REFERENCES "users"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "report_revisions_report_index" ON "report_revisions" ("report_id", "id");
