-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "rollup_states" (
  "id" BIGSERIAL PRIMARY KEY,
  "project_id" bigint not null REFERENCES "projects"("id"),
  "covered_from" varchar(10),
  "covered_through" varchar(10),
  "timezone" varchar(64) default 'UTC',
  "built_at" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "rollup_states_project_unique" ON "rollup_states" ("project_id");
