-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "events" ALTER COLUMN "properties" DROP DEFAULT;
ALTER TABLE "events" ALTER COLUMN "properties" TYPE text USING "properties"::text;
ALTER TABLE "events" ALTER COLUMN "properties" DROP NOT NULL;
ALTER TABLE "report_blocks" ALTER COLUMN "query" DROP DEFAULT;
ALTER TABLE "report_blocks" ALTER COLUMN "query" TYPE text USING "query"::text;
ALTER TABLE "report_blocks" ALTER COLUMN "query" DROP NOT NULL;
ALTER TABLE "report_blocks" ALTER COLUMN "viz" DROP DEFAULT;
ALTER TABLE "report_blocks" ALTER COLUMN "viz" TYPE text USING "viz"::text;
ALTER TABLE "report_blocks" ALTER COLUMN "viz" DROP NOT NULL;
