-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "report_shares" (
  "id" BIGSERIAL PRIMARY KEY,
  "report_id" bigint not null REFERENCES "reports"("id"),
  "token" varchar(80) not null,
  "label" varchar(120),
  "expires_at" varchar(255),
  "revoked_at" varchar(255),
  "view_count" integer default 0,
  "last_viewed_at" varchar(255),
  "show_branding" boolean default true,
  "created_by_id" bigint REFERENCES "users"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "report_shares_token_unique" ON "report_shares" ("token");
CREATE INDEX IF NOT EXISTS "report_shares_report_index" ON "report_shares" ("report_id");
CREATE UNIQUE INDEX IF NOT EXISTS "report_shares_token_unique" ON "report_shares" ("token");
