-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "project_invites" (
  "id" BIGSERIAL PRIMARY KEY,
  "project_id" bigint not null REFERENCES "projects"("id"),
  "email" varchar(255) not null,
  "role" "project_invites_role_type" default 'member',
  "token" varchar(80),
  "expires_at" varchar(255),
  "accepted_at" varchar(255),
  "revoked_at" varchar(255),
  "invited_by_id" bigint REFERENCES "users"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "project_invites_token_unique" ON "project_invites" ("token");
CREATE INDEX IF NOT EXISTS "project_invites_project_email_index" ON "project_invites" ("project_id", "email");
CREATE UNIQUE INDEX IF NOT EXISTS "project_invites_token_unique" ON "project_invites" ("token");
