-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "report_exports" (
  "id" BIGSERIAL PRIMARY KEY,
  "report_id" bigint not null REFERENCES "reports"("id"),
  "format" "report_exports_format_type" not null,
  "status" "report_exports_status_type" default 'pending',
  "range_from" varchar(255),
  "range_to" varchar(255),
  "path" varchar(500),
  "size_bytes" integer,
  "error" varchar(500),
  "expires_at" varchar(255),
  "requested_by_id" bigint REFERENCES "users"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "report_exports_report_index" ON "report_exports" ("report_id", "id");
CREATE INDEX IF NOT EXISTS "report_exports_expiry_index" ON "report_exports" ("expires_at");
