-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "event_rollups" ALTER COLUMN "value_sum" DROP DEFAULT;
ALTER TABLE "event_rollups" ALTER COLUMN "value_sum" TYPE real USING "value_sum"::real;
ALTER TABLE "event_rollups" ALTER COLUMN "value_sum" DROP NOT NULL;
ALTER TABLE "event_rollups" ALTER COLUMN "value_sum" SET default 0;
ALTER TABLE "event_rollups" ALTER COLUMN "value_min" DROP DEFAULT;
ALTER TABLE "event_rollups" ALTER COLUMN "value_min" TYPE real USING "value_min"::real;
ALTER TABLE "event_rollups" ALTER COLUMN "value_min" DROP NOT NULL;
ALTER TABLE "event_rollups" ALTER COLUMN "value_max" DROP DEFAULT;
ALTER TABLE "event_rollups" ALTER COLUMN "value_max" TYPE real USING "value_max"::real;
ALTER TABLE "event_rollups" ALTER COLUMN "value_max" DROP NOT NULL;
