-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "report_schedules" (
  "id" BIGSERIAL PRIMARY KEY,
  "report_id" bigint not null REFERENCES "reports"("id"),
  "cadence" "report_schedules_cadence_type" default 'weekly',
  "hour" integer default 8,
  "day_of_week" integer,
  "day_of_month" integer,
  "timezone" varchar(64) default 'UTC',
  "recipients" text not null,
  "format" "report_schedules_format_type" default 'link',
  "is_active" boolean default true,
  "next_run_at" varchar(255),
  "last_run_at" varchar(255),
  "last_status" varchar(200),
  "created_by_id" bigint REFERENCES "users"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "report_schedules_active_index" ON "report_schedules" ("is_active", "next_run_at");
CREATE INDEX IF NOT EXISTS "report_schedules_report_index" ON "report_schedules" ("report_id");
