-- @generated by `buddy migrate:regenerate` — edits will be overwritten
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_event_rollups" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "project_id" INTEGER not null REFERENCES "projects"("id"),
  "day" TEXT not null,
  "name" TEXT not null,
  "event_count" INTEGER default 0,
  "value_sum" REAL default 0,
  "value_count" INTEGER default 0,
  "value_min" REAL,
  "value_max" REAL,
  "unique_users" INTEGER default 0,
  "built_at" TEXT
);
INSERT INTO "_qb_tmp_event_rollups" ("id", "project_id", "day", "name", "event_count", "value_sum", "value_count", "value_min", "value_max", "unique_users", "built_at") SELECT "id", "project_id", "day", "name", "event_count", "value_sum", "value_count", "value_min", "value_max", "unique_users", "built_at" FROM "event_rollups";
DROP TABLE "event_rollups";
ALTER TABLE "_qb_tmp_event_rollups" RENAME TO "event_rollups";
CREATE UNIQUE INDEX IF NOT EXISTS "event_rollups_unique" ON "event_rollups" ("project_id", "day", "name");
CREATE INDEX IF NOT EXISTS "event_rollups_project_day_index" ON "event_rollups" ("project_id", "day");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
