-- @generated by `buddy migrate:regenerate` — edits will be overwritten
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_events" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "project_id" INTEGER not null REFERENCES "projects"("id"),
  "name" TEXT not null,
  "occurred_at" TEXT not null,
  "received_at" TEXT,
  "properties" TEXT,
  "value" REAL,
  "currency" TEXT,
  "user_key" TEXT,
  "session_key" TEXT
);
INSERT INTO "_qb_tmp_events" ("id", "project_id", "name", "occurred_at", "received_at", "properties", "value", "currency", "user_key", "session_key") SELECT "id", "project_id", "name", "occurred_at", "received_at", "properties", "value", "currency", "user_key", "session_key" FROM "events";
DROP TABLE "events";
ALTER TABLE "_qb_tmp_events" RENAME TO "events";
CREATE INDEX IF NOT EXISTS "events_project_name_time_index" ON "events" ("project_id", "name", "occurred_at");
CREATE INDEX IF NOT EXISTS "events_project_time_index" ON "events" ("project_id", "occurred_at");
CREATE INDEX IF NOT EXISTS "events_project_user_index" ON "events" ("project_id", "user_key");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
