-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "report_shares" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "report_id" INTEGER not null REFERENCES "reports"("id"),
  "token" TEXT not null,
  "label" TEXT,
  "expires_at" TEXT,
  "revoked_at" TEXT,
  "view_count" INTEGER default 0,
  "last_viewed_at" TEXT,
  "show_branding" INTEGER default 1,
  "created_by_id" INTEGER REFERENCES "users"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "report_shares_token_unique" ON "report_shares" ("token");
CREATE INDEX IF NOT EXISTS "report_shares_report_index" ON "report_shares" ("report_id");
CREATE UNIQUE INDEX IF NOT EXISTS "report_shares_token_unique" ON "report_shares" ("token");
