-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "rollup_states" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "project_id" INTEGER not null REFERENCES "projects"("id"),
  "covered_from" TEXT,
  "covered_through" TEXT,
  "timezone" TEXT default 'UTC',
  "built_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "rollup_states_project_unique" ON "rollup_states" ("project_id");
