-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "report_blocks" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "report_id" INTEGER not null REFERENCES "reports"("id"),
  "kind" TEXT CHECK ("kind" IN ('line', 'area', 'bar', 'donut', 'big_number', 'table', 'funnel', 'heatmap', 'text')) not null,
  "title" TEXT,
  "x" INTEGER default 0,
  "y" INTEGER default 0,
  "w" INTEGER default 6,
  "h" INTEGER default 4,
  "query" TEXT,
  "viz" TEXT,
  "body" TEXT,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE INDEX IF NOT EXISTS "report_blocks_report_index" ON "report_blocks" ("report_id");
