-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "report_revisions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "report_id" INTEGER not null REFERENCES "reports"("id"),
  "snapshot" TEXT not null,
  "reason" TEXT CHECK ("reason" IN ('autosave', 'publish', 'restore')) default 'autosave',
  "created_by_id" INTEGER REFERENCES "users"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE INDEX IF NOT EXISTS "report_revisions_report_index" ON "report_revisions" ("report_id", "id");
