-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "event_rollups" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "project_id" INTEGER not null REFERENCES "projects"("id"),
  "day" TEXT not null,
  "name" TEXT not null,
  "event_count" INTEGER default 0,
  "value_sum" INTEGER default 0,
  "value_count" INTEGER default 0,
  "value_min" INTEGER,
  "value_max" INTEGER,
  "unique_users" INTEGER default 0,
  "built_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "event_rollups_unique" ON "event_rollups" ("project_id", "day", "name");
CREATE INDEX IF NOT EXISTS "event_rollups_project_day_index" ON "event_rollups" ("project_id", "day");
