-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "report_schedules" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "report_id" INTEGER not null REFERENCES "reports"("id"),
  "cadence" TEXT CHECK ("cadence" IN ('daily', 'weekly', 'monthly')) default 'weekly',
  "hour" INTEGER default 8,
  "day_of_week" INTEGER,
  "day_of_month" INTEGER,
  "timezone" TEXT default 'UTC',
  "recipients" TEXT not null,
  "format" TEXT CHECK ("format" IN ('link', 'csv', 'xlsx')) default 'link',
  "is_active" INTEGER default 1,
  "next_run_at" TEXT,
  "last_run_at" TEXT,
  "last_status" TEXT,
  "created_by_id" INTEGER REFERENCES "users"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE INDEX IF NOT EXISTS "report_schedules_active_index" ON "report_schedules" ("is_active", "next_run_at");
CREATE INDEX IF NOT EXISTS "report_schedules_report_index" ON "report_schedules" ("report_id");
