-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "project_invites" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "project_id" INTEGER not null REFERENCES "projects"("id"),
  "email" TEXT not null,
  "role" TEXT CHECK ("role" IN ('admin', 'member')) default 'member',
  "token" TEXT,
  "expires_at" TEXT,
  "accepted_at" TEXT,
  "revoked_at" TEXT,
  "invited_by_id" INTEGER REFERENCES "users"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "project_invites_token_unique" ON "project_invites" ("token");
CREATE INDEX IF NOT EXISTS "project_invites_project_email_index" ON "project_invites" ("project_id", "email");
CREATE UNIQUE INDEX IF NOT EXISTS "project_invites_token_unique" ON "project_invites" ("token");
