-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "project_members" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "project_id" INTEGER not null REFERENCES "projects"("id"),
  "user_id" INTEGER not null REFERENCES "users"("id"),
  "email" TEXT,
  "role" TEXT CHECK ("role" IN ('admin', 'member')) default 'member',
  "invited_by_id" INTEGER,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "project_members_project_user_unique" ON "project_members" ("project_id", "user_id");
CREATE INDEX IF NOT EXISTS "project_members_user_index" ON "project_members" ("user_id");
