-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "reports" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "project_id" INTEGER not null REFERENCES "projects"("id"),
  "name" TEXT not null,
  "slug" TEXT,
  "description" TEXT,
  "status" TEXT CHECK ("status" IN ('draft', 'published')) default 'draft',
  "origin" TEXT CHECK ("origin" IN ('user', 'template')) default 'user',
  "template_key" TEXT,
  "template_version" INTEGER,
  "default_range" TEXT default 'last_30_days',
  "created_by_id" INTEGER REFERENCES "users"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "deleted_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "reports_project_slug_unique" ON "reports" ("project_id", "slug");
CREATE INDEX IF NOT EXISTS "reports_project_template_index" ON "reports" ("project_id", "template_key");
CREATE UNIQUE INDEX IF NOT EXISTS "reports_uuid_unique" ON "reports" ("uuid");
