-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "report_exports" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "report_id" INTEGER not null REFERENCES "reports"("id"),
  "format" TEXT CHECK ("format" IN ('csv', 'xlsx')) not null,
  "status" TEXT CHECK ("status" IN ('pending', 'running', 'ready', 'failed')) default 'pending',
  "range_from" TEXT,
  "range_to" TEXT,
  "path" TEXT,
  "size_bytes" INTEGER,
  "error" TEXT,
  "expires_at" TEXT,
  "requested_by_id" INTEGER REFERENCES "users"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE INDEX IF NOT EXISTS "report_exports_report_index" ON "report_exports" ("report_id", "id");
CREATE INDEX IF NOT EXISTS "report_exports_expiry_index" ON "report_exports" ("expires_at");
