-- @generated by `buddy migrate:regenerate` — edits will be overwritten
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_report_revisions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "report_id" INTEGER not null REFERENCES "reports"("id"),
  "snapshot" TEXT not null,
  "reason" TEXT CHECK ("reason" IN ('autosave', 'publish', 'restore', 'upgrade')) default 'autosave',
  "created_by_id" INTEGER REFERENCES "users"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
INSERT INTO "_qb_tmp_report_revisions" ("id", "report_id", "snapshot", "reason", "created_by_id", "created_at", "updated_at") SELECT "id", "report_id", "snapshot", "reason", "created_by_id", "created_at", "updated_at" FROM "report_revisions";
DROP TABLE "report_revisions";
ALTER TABLE "_qb_tmp_report_revisions" RENAME TO "report_revisions";
CREATE INDEX IF NOT EXISTS "report_revisions_report_index" ON "report_revisions" ("report_id", "id");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
