-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "events" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "project_id" INTEGER not null REFERENCES "projects"("id"),
  "name" TEXT not null,
  "occurred_at" TEXT not null,
  "received_at" TEXT,
  "properties" TEXT,
  "value" INTEGER,
  "currency" TEXT,
  "user_key" TEXT,
  "session_key" TEXT
);
CREATE INDEX IF NOT EXISTS "events_project_name_time_index" ON "events" ("project_id", "name", "occurred_at");
CREATE INDEX IF NOT EXISTS "events_project_time_index" ON "events" ("project_id", "occurred_at");
CREATE INDEX IF NOT EXISTS "events_project_user_index" ON "events" ("project_id", "user_key");
