-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "projects" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "slug" TEXT,
  "ingest_key" TEXT,
  "timezone" TEXT default 'UTC',
  "auto_reports_enabled" INTEGER default 1,
  "first_event_at" TEXT,
  "owner_id" INTEGER REFERENCES "users"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "deleted_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "projects_ingest_key_unique" ON "projects" ("ingest_key");
CREATE INDEX IF NOT EXISTS "projects_owner_index" ON "projects" ("owner_id");
CREATE UNIQUE INDEX IF NOT EXISTS "projects_ingest_key_unique" ON "projects" ("ingest_key");
CREATE UNIQUE INDEX IF NOT EXISTS "projects_uuid_unique" ON "projects" ("uuid");
